version: '3.8'

services:
  spoon-parser:
    build: .
    container_name: spoon-parser
    environment:
      - INPUT_DIR=/input
      - OUTPUT_FILE=/output/parse-result.json
      - JAVA_OPTS=-Xmx4g -Xms1g
    volumes:
      # Mount the directory containing Java source code
      - "${JAVA_SOURCE_PATH:-./sample-java}:/input:ro"
      # Mount the output directory
      - "${OUTPUT_PATH:-./output}:/output"
    # Override entrypoint for debugging if needed
    # command: ["tail", "-f", "/dev/null"]